services:
  - type: web
    name: youtube-downloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --config gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: DOWNLOAD_FOLDER
        value: /tmp/downloads